---
kind: pipeline
name: ci

steps:
  - name: install
    image: iknpx/archnode
    commands:
      - yarn --silent
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name: lint
    image: iknpx/archnode
    commands:
      - yarn lint
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name: make/image
    image: plugins/docker
    settings:
      repo: iknpx/portyx-api
      purge: true
      insecure: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      token:
        from_secret: docker_token
    when:
      branch:
        - master
        - develop
      event:
        - push
