---
kind: pipeline
name: ci

steps:
  - name: install
    image: iknpx/archnode
    commands:
      - yarn --silent
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name: lint
    image: iknpx/archnode
    commands:
      - yarn lint
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name: make/image
    image: plugins/docker
    settings:
      repo: docker.pkg.github.com/iknpx/repository-name/portyx-api
      purge: true
      insecure: false
      auth:
        from_secret: docker_token
      username:
        from_secret: docker_username
    when:
      branch:
        - master
        - develop
      event:
        - push
